version: "2"
services:
  neo4j:
    image: neo4j:latest
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - "$HOME/neo4j/data:/home/emilio/Documents/git/public/scratch/neo4j_basics/data"
    environment:
      NEO4J_AUTH: none
